networks:
  dev:

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
      - "/etc/letsencrypt:/etc/letsencrypt"
    depends_on:
      - backend
      - frontend
    networks:
      - dev

  mongo:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: "root"
      MONGO_INITDB_ROOT_PASSWORD: "root"
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - dev

  backend:
    build:
      context: ./server

    volumes:
      - "./server/upload:/app/upload"
    networks:
      - dev
    depends_on:
      - mongo
    environment:
      PORT: 8000
      NODE_ENV: "development"
      URL_DB: "mongodb://root:root@31.129.59.181:27017"
      CLIENT_URL: "https://debilgram.ru"
      SERVER_URL: "https://api.debilgram.ru"
      JWT_ACCESS_EXPIRES_IN: "15m"
      JWT_REFRESH_EXPIRES_IN: "7d"
      JWT_ACCESS_SECRET: "prakt-good-ready-and-good-not-let"
      JWT_REFRESH_SECRET: "gg-prak-very-bad-and-suck-tired"
      JWT_COOKIE_EXPIERS_IN: 7
      CHECK_SECRET: ${CHECK_SECRET}

  frontend:
    build:
      context: ./frontend
    networks:
      - dev
    depends_on:
      - backend
    environment:
      VITE_API_URL: "https://api.debilgram.ru/api/v1"
      VITE_SOCKET_URL: "https://api.debilgram.ru/"

volumes:
  mongo-data:
