on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run_pull:
    name: run pull
    runs-on: ubuntu-latest

    steps:
      - name: install ssh keys
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SERVER_IP }} > ~/.ssh/known_hosts

      - name: connect and pull
        run: ssh ${{ secrets.USER }}@${{ secrets.SERVER_IP }} "cd docker-mern && touch .env && echo URL_DB=${{ secrets.URL_DB}} >> .env && cd frontend && touch .env && echo VITE_CHECK_URL=${{ secrets.CHECK_SECRET }} >> .env && cd .. && git pull && docker compose up --build -d"
      - name: cleanup
        run: rm -rf ~/.ssh
