name: Deploy to Server

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up SSH
      run: |
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key
        chmod 600 private_key
        eval $(ssh-agent -s)
        ssh-add private_key
      shell: bash

    - name: Run commands on Server
      env: 
        CHECK_SECRET: ${{ secrets.CHECK_SECRET }}
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.USER }}@${{ secrets.SERVER_IP }} << 'EOF'
          cd docker-mern
          git pull
          docker compose up --build -d 
        EOF
